## Introduction

Tensors are the core data structure in PyTorch. Through creating and working with tensors, you will learn how tensors are similar to NumPy arrays, but offer additional features for deep learning.

## Setup

### Import Libraries

In [87]:
import torch
import torch.nn as nn

## Section 1: `torch.tensor()` works like numpy arrays

PyTorch's fundamental data structure is the tensor, which works similarly to NumPy arrays. Tensors can hold scalars, vectors, matrices, or higher-dimensional data. You can create them directly from Python lists, generate sequences with `torch.linspace`, and initialize them as zeros or ones.

| Code | Description |
| :-- | :-- |
| `torch.tensor(2)` | Creates a tensor containing the scalar value 2. |
| `torch.tensor([0,1,2])` | Creates a tensor containing the vector with values 0, 1, and 2. |
| `torch.tensor([[1,2,3], [4,5,6]])` | Creates a 2-dimensional tensor of size 2x3 containing the values from 1 to 6. |
| `torch.linspace(0,5,11)` | Initializes a 1D tensor with the numbers from 0 to 5 with 0.5 spacing. |
| `torch.zeros(10)` | Initializes a 1D tensor of size 10 filled with zeros. |
| `torch.zeros(2,3)` | Initializes a 2D tensor of dimensions 2x3 filled with zeros. |
| `torch.ones(1-)` | Initializes a 1D tensor of size 10 filled with ones. |
| `x.shape` | Get the shape of the tensor. |
| `x.reshape(2, 3)` | Reshape the tensor to a new shape. |

**Example**: Create a tensor of the scalar value 10.

In [3]:
torch.tensor(10)

tensor(10)

**Exercise**: Create a tensor containing the vector with values 1, 2, 3, 4, and 5.

In [4]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

**Exercise**: Create a 2-dimensional tensor of size 3x2 containing the values 1, 2, 3, 4, 5, and 6.

In [5]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

**Exercise**: Create a tensor `x` with values 1 through 6 and check its shape using `.shape`.

In [6]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x.shape

torch.Size([6])

**Exercise**: Reshape the tensor `x` from above into a 2x3 matrix using `.reshape()`.

In [7]:
x.reshape(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

**Exercise**: Create a 1D tensor of size 5 filled with zeros using `torch.zeros()`.

In [8]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

**Exercise**: Create a 2D tensor of dimensions 2x3 filled with zeros using `torch.zeros()`.

In [9]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

**Exercise**: Create a 1D tensor of size 5 filled with ones using `torch.ones()`.

In [10]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

**Exercise**: Use `torch.linspace` to create a 1D tensor with 5 evenly spaced numbers from 0 to 10.

In [11]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## Section 2: Calculating Loss (MSE, Absolute Error)

| Code | Description |
| :-- | :-- |
| `(y_pred - y_obs).abs()` | Calculate the absolute error between prediction and observation. |
| `(y_pred - y_obs)**2` | Calculate the squared error between prediction and observation. |
| `(y_pred - y_obs).abs().mean()` | Calculate the mean absolute error (loss) between prediction and observation. |
| `((y_pred - y_obs)**2).mean()` | Calculate the mean squared error (loss) between prediction and observation. |


**Example**: Calculate the loss as the absolute error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `6`.

In [69]:
y_pred = torch.tensor(4.0)
y_obs = torch.tensor(10.0)

In [70]:
((y_pred - y_obs)).abs().mean()

tensor(6.)

**Exercise**: Calculate the loss as the absolute error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `4`.

In [71]:
y_pred = torch.tensor(6.0)
y_obs = torch.tensor(10.0)

In [72]:
((y_pred - y_obs)).abs().mean()

tensor(4.)

**Exercise**: Here, we have multiple (two) predictions and observations that we compare them to. Calculate the loss as the mean absolute error between the predicted values `y_pred` and observed data `y_obs` defined below. The correct answer is `5`.

In [73]:
y_pred = torch.tensor([4.0, 6.0])
y_obs = torch.tensor([10.0, 10.0])

In [74]:
((y_pred - y_obs)).abs().mean()

tensor(5.)

**Exercise**: Calculate the loss as the mean square error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `36`.

In [75]:
y_pred = torch.tensor(4.0)
y_obs = torch.tensor(10.0)

In [76]:
((y_pred - y_obs)**2).mean()

tensor(36.)

**Exercise**: Calculate the loss as the mean square error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `16`.

In [77]:
y_pred = torch.tensor(6.0)
y_obs = torch.tensor(10.0)

In [78]:
((y_pred - y_obs)**2).mean()

tensor(16.)

**Exercise**: Calculate the loss as the mean square error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `10`.

In [79]:
y_pred = torch.tensor([6.0, 8.0])
y_obs = torch.tensor([10.0, 10.0])

In [80]:
((y_pred - y_obs)**2).mean()

tensor(10.)

**Exercise**: Calculate the loss as the mean square error between the predicted value `y_pred` and observed data `y_obs` defined below. The correct answer is `3`.

In [85]:
y_pred = torch.tensor([7.0, 10.0, 12.0])
y_obs = torch.tensor([10.0, 10.0, 12.0])

In [86]:
((y_pred - y_obs)**2).mean()

tensor(3.)

## Section 3: Loss in PyTorch

In the previous section, you calculated the loss manually using the formula for mean squared error. PyTorch provides built-in loss functions through its `nn` module that do this calculation for you. Here, you'll practice using the built-in function `nn.MSELoss()` to calculate the mean squared error loss.

| Code | Description |
| :-- | :-- |
| `model(X_input)` | Pass input `X_input` to a neural network `model`. |
| `y_pred = model(X_input)` | Pass input `X_input` to a neural network `model` and assign the output to a variable `y_pred`. |
| `nn.MSELoss()` | Creates a mean squared error (MSE) loss function. |
| `loss_fn = nn.MSELoss()` | Creates a mean squared error (MSE) loss function and assigns it to a variable named `loss_fn`. |
| `nn.MSELoss()(y_pred, y_obs)` | Creates a mean squared error (MSE) loss function and immediately uses it to calculate the loss. |
| `loss_fn(y_pred, y_obs)` | Uses the loss function variable to calculate the loss between the prediction `y_pred` and the<br>observed values `y_obs`. |
| `loss_fn(y_pred, y_obs).item()` | Extracts the loss value from the tensor. |
| `loss = loss_fn(y_pred, y_obs).item()` | Extracts the loss value from the tensor and assigns it to a variable `loss`. |

**Example**: Create a mean sqare error loss function using PyTorch's `nn` module.

In [ ]:
nn.MSELoss()

MSELoss()

**Exercise**: Create a mean sqare error loss function using PyTorch's `nn` module and assign it to a variable named `loss_fn`. Display the `loss_fn` variable.

In [ ]:
loss_fn = nn.MSELoss()
loss_fn

MSELoss()

Run the cell below to calculate the mean square error loss between `y_pred` and `y_obs` manually (like in the previous section).

In [93]:
x = torch.tensor(2.0)
a = torch.tensor(3.0) # initial guess
y_pred = a * x

y_obs = torch.tensor(10.0)

print(f'loss: {((y_pred-y_obs)**2).mean()}')

loss: 16.0


**Exercise**: Instead of calculating it manually, use the `nn` module's mean square error loss function to calculate the loss between `y_pred` and `y_obs`.

In [94]:
nn.MSELoss()(y_pred, y_obs)

tensor(16.)

**Exercise**: Use the loss function variable `loss_fn` defined below to calculate mean square error loss function to calculate the loss between the `y_pred` and `y_obs`.

In [95]:
loss_fn = nn.MSELoss()

In [ ]:
loss_fn(y_pred, y_obs)

tensor(16.)

**Exercise**: Calculate the loss using either of the methods above and extract the number from the tensor. When you display the result, it will just say `16.0` instead of `tensor(16)`.

**Hint**: See code reference table.

In [97]:
loss_fn(y_pred, y_obs).item()

16.0

**Exercise**: Calculate the loss using either of the methods above, extract the number as a float from the loss tensor, and assign this number to a variable named `loss`. Display the `loss` variable.

In [98]:
loss = loss_fn(y_pred, y_obs).item()
loss

16.0

## Section 4: Different Problems Require Different Kinds of Loss Functions

So far, we've used mean squared error (MSE) as our loss function. MSE works well for regression problems, where we're trying to predict a continuous value like a firing rate or a price. But not all machine learning problems are regression problems. In classification problems, we're trying to predict which category something belongs to - for example, whether an image shows a cat or a dog, or which type of stimulus was presented to the animal in an experiment. For these problems, MSE doesn't work well because we're not measuring distance from a target value, we're measuring how confident the model is in its class prediction. PyTorch provides different loss functions for different types of problems:

- **MSE Loss** (`nn.MSELoss()`): For regression - predicting continuous values
- **Binary Cross-Entropy** (`nn.BCEWithLogitsLoss()`): For binary classification - two classes
- **Cross-Entropy** (`nn.CrossEntropyLoss()`): For multiclass classification - more than two classes

In all cases, the loss measures how wrong the model's predictions are. Lower loss means better predictions, and training a neural network means finding parameters that minimize the loss.

| Code | Description |
| --- | --- |
| `nn.MSELoss()` | Creates a mean squared error (MSE) loss function. Used for regression problems. |
| `nn.BCEWithLogitsLoss()` | Creates a binary cross-entropy loss function. Used for binary classification (two classes). |
| `nn.CrossEntropyLoss()` | Creates a cross-entropy loss function. Used for multiclass classification (more than two classes). |
| `loss_fn(y_pred, y_true)` | Calculates the loss between predictions `y_pred` and true values `y_true`. |
| `loss_fn(y_pred, y_true).item()` | Extracts the loss value as a `float` from the tensor. |

**Example**: Create a binary cross-entropy loss function using PyTorch's `nn` module.

In [ ]:
nn.BCEWithLogitsLoss()

**Exercise**: Create a binary cross-entropy loss function using PyTorch's `nn` module and assign it to a variable named `loss_fn`. Display the variable.

In [ ]:
loss_fn = nn.BCEWithLogitsLoss()
loss_fn

**Exercise**: Create a cross-entropy loss function for multiclass classification using PyTorch's `nn` module and assign it to a variable named `loss_fn`. Display the variable.

In [ ]:
loss_fn = nn.CrossEntropyLoss()
loss_fn

CrossEntropyLoss()

Below we simulate a binary classification scenario. Imagine we have a model that predicts whether a neuron is "active" (1) or "inactive" (0) based on some input. The model outputs a raw score (called a "logit"). Positive values suggest "active", negative values suggest "inactive". Run the cell to print the output of the model (the raw score) and the true labels.

In [ ]:
# simulated model outputs (logits) for 4 samples
# Positive values = model thinks "active", negative = model thinks "inactive"
y_pred = torch.tensor([2.0, -1.0, 0.5, -2.0])

# True labels: 1 = active, 0 = inactive
y_true = torch.tensor([1.0, 0.0, 1.0, 0.0])

print(f"Model predictions (logits): {y_pred}")
print(f"True labels: {y_true}")

Model predictions (logits): tensor([ 2.0000, -1.0000,  0.5000, -2.0000])
True labels: tensor([1., 0., 1., 0.])


**Example**:  Calculate the binary cross-entropy loss for the model prediction above.

In [ ]:
# create the binary cross-entropy loss function
loss_fn = nn.BCEWithLogitsLoss()
# calculate binary cross-entropy loss
loss = loss_fn(y_pred, y_true)

print(f"Binary cross-entropy loss: {loss.item():.4f}")

Binary cross-entropy loss: 0.2603


**Exercise**: The cell below contains a different set of predictions for the same true labels. The model made worse predictions this time (the signs of the logits don't match the true labels as well). Calculate the binary cross-entropy loss. Is the loss higher or lower than in the example above?

In [ ]:
# bad predictions - signs often don't match true labels
y_pred = torch.tensor([-1.0, 1.0, -0.5, 1.0])

# True labels (same as before)
y_true = torch.tensor([1.0, 0.0, 1.0, 0.0])

In [ ]:
loss_bad = loss_fn(y_pred, y_true)
print(f"Binary cross-entropy loss: {loss_bad.item():.4f}")

# The loss is higher because the predictions are worse

Binary cross-entropy loss: 1.2285


Below, we simulate multiclass classification. For multiclass classification, the model outputs a score for each possible class. Our hypothetical model that classifies images into 3 categories indicating where the stimulus was presented: "stimulus left" (0), "stimulus middle" (1), or "stimulus right" (2). The model outputs 3 scores per sample - higher scores indicate higher confidence in that class.

In [ ]:
# model outputs for 3 samples, with 3 classes each (stimulus left, stimulus middle, stimulus right)
# each row is one sample, each column is the score for one class
y_pred = torch.tensor([
    [2.0, 0.5, -1.0],   # Sample 1: highest score for stimulus left (index 0)
    [-1.0, 2.5, 0.0],   # Sample 2: highest score for stimulus middle (index 1)
    [0.0, -0.5, 3.0]    # Sample 3: highest score for stimulus right (index 2)
])

# true labels (class indices): stimulus left=0, stimulus middle=1, stimulus right=2
y_true = torch.tensor([0, 1, 2])

print(f"Model predictions (logits):\n{y_pred}")
print(f"True labels: {y_true}")

Model predictions (logits):
tensor([[ 2.0000,  0.5000, -1.0000],
        [-1.0000,  2.5000,  0.0000],
        [ 0.0000, -0.5000,  3.0000]])
True labels: tensor([0, 1, 2])


In [ ]:
# calculate cross-entropy loss
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_pred, y_true)

print(f"Cross-entropy loss: {loss.item():.4f}")

Cross-entropy loss: 0.1416


**Exercise**: The cell below contains predictions where the model made some mistakes (the highest scores don't always match the true labels). Calculate the cross-entropy loss using the `loss_fn` defined above. Is the loss higher or lower than in the example?

In [ ]:
# bad predictions - highest scores don't match true labels
y_pred = torch.tensor([
    [0.5, 2.0, -1.0],   # Sample 1: highest score for stimulus middle, but true label is stimulus left
    [-1.0, 2.5, 0.0],   # Sample 2: highest score for stimulus middle (correct)
    [2.0, -0.5, 1.0]    # Sample 3: highest score for stimulus left, but true label is stimulus right
])

# True labels (same as before)
y_true = torch.tensor([0, 1, 2])

In [ ]:
loss_bad = loss_fn(y_pred, y_true)
print(f"Cross-entropy loss: {loss_bad.item():.4f}")

# The loss is higher because the predictions are worse

Cross-entropy loss: 1.0731
