## Setup

### Import Libraries

In [1]:
import torch
import torch.nn as nn
import numpy as np

## Section 1: Machine Learning is iterative guessing.  Iteration can be done with For Loops.

When you train a neural network, you're making the model guess what the output should be over and over again. Between each guess, the model parameters are updated until the guess is good enough. In other words, it's an iterative improvement of the model. This iteration can be programmed with a for loop. A for loop lets us perform an operation a predefined number of times and is an incredibly useful programming concept. In this section, you will get som practice writing for loops.

| Code | Description |
| --- | --- |
| `for letter in ["a", "b", "c"]:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(letter)` | Print every `letter` in the list `["a", "b", "c"]`|
| `for i in range(5):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every number `i` between 0 and 5 (not including 5)|
| `for i in range(2, 7):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every number `i` between 2 and 7 (not including 7)|
| `for i in range(1, 10, 2):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every **second** number `i` between 1 and 10 (not including 10)|
| `for x_i in x:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(x_i)` | Print every element `x_i` in the collection `x`|
| `for x_i in x:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `for y_i in y`: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `print(x_i, y_i)` | Print every element `x_i` and `y_i` in the collections `x` and `y`|
| `new_list = []` or `new_list = list()`| Initialize an empty list named `new_list` |
| `new_list.append(element)`| Append an element to the list `new_list` |

#### **Exercises**

**Example**: Write a for loop that prints the numbers **0** to **9**.

In [3]:
for num in range(9):
    print(num)

0
1
2
3
4
5
6
7
8


**Exercise**: Write a for loop that prints the numbers **5** to **10**.


In [4]:
for i in range(5,10):
    print(i)

5
6
7
8
9


**Exercise**: Write a for loop that counts from **0** to **100** in steps of **10**.

In [5]:
for j in range(0,100,10):
    print(j)

0
10
20
30
40
50
60
70
80
90


**Exercise**: Nested loops: Use loops to print all `fruits` and `colors`, for example `banana is yellow"`.

In [6]:
# provided

fruits = ["banana", "orange", "cherry"]
colors= ["yellow", "orange", "green"];

In [7]:
for fruit in fruits:
    for color in colors:
        print(fruit+' is '+color)

banana is yellow
banana is orange
banana is green
orange is yellow
orange is orange
orange is green
cherry is yellow
cherry is orange
cherry is green


**Exercise**: Write a loop that calculates the square of each element in `numbers` and stores the result in a new list called `squared_numbers`. Display the `squared_numbers` list at the end to check that it is correct.

In [8]:
numbers = [4, 6, 12, 50]

In [9]:
squared_numbers = []

for i in range(len(numbers)):
    num_squared = numbers[i]**2
    squared_numbers.append(num_squared)

squared_numbers

[16, 36, 144, 2500]

**Exercise**: Write a loop that multiplies each element in the list `numbers` by 4 and store the results in a new list called `multiplied_numbers`. Display `multiplied_numbers` to check that it is correct.

In [10]:
numbers = [4, 6, 12, 50]

In [11]:
multiplied_numbers = []
for num in numbers:
    mult_number = 4*num

    multiplied_numbers.append(mult_number)

multiplied_numbers

[16, 24, 48, 200]

## Section 2: Machine Learning is Adjusting Guesses Based on Loss (Error) 

To improve the model between each guess, we need to know how close the model was to getting the right answer. In other words, we need to know the difference between the model's guess and the true value. This is referred to as the "loss", and machine learning is all about minimizing this loss. In this section, we'll learn how to calculate the loss and explore it's role is in updating parameters between iterations.

| Code | Description |
| --- | --- |
| `param = param - learning_rate * gradient_param` | Update the parameter `param`. |
| `z**2` | Calculate the square of z. |
| `y_pred = a * x` | Make a prediction using parameter `a` and input `x`. |
| `(y_pred - y_obs)**2` | Calculate the squared error (loss) between prediction and observation. |
| `grad_a = -2 * (y_obs - y_pred) * x` | Calculate the gradient of the loss with respect to parameter `a`. |
| `a = a - learning_rate * grad_a` | Update parameter `a` using the gradient and learning rate. |
| `learning_rate = some_num` | Define the learning rate hyperparameter, which controls the step size of gradient descent. |

We want to quantify the relationship between the firing rate of a neuron in visual cortex and the brightness of a stimulus. Let's suppose that it's described by a simple linear equation where `x` is stimulus strength and `y` is the firing rate of the neuron:

$$y = a \times x$$

But we don't know the parameter `a`, so we start by just taking a guess. We guess that `a = 2` and predict the firing rate for stimulus strength `x = 2` using the equation above. That gives us the predicted firing rate `y_pred = 4` Hz. Now, we compare this prediction to our recorded data to see how good it was.

**Example**: Calculate the loss between the predicted firing rate `y_pred` and the observed firing rate `y_obs` using mean square error. Display the loss.

In [27]:
x = 2

a = 3 # initial guess

y_pred = a * x # Hz
y_obs = 10 # Hz

In [28]:
loss = np.mean((y_pred-y_obs)**2)
print(f'loss: {loss}')

loss: 16.0


Since that guess was off, we make a new guess. We guess that `a = 1`, which gives us a new firing rate prediction using the same equation as above: `y_pred = 2`

**Exercise**: Calculate the loss between the predicted firing rate `y_pred` and the observed firing rate `y_obs` using mean square error. Display the loss.

In [34]:
x = 2

a = 1 # new guess

y_pred = a * x # Hz
y_obs = 10 # Hz

In [35]:
loss = np.mean((y_pred-y_obs)**2)
loss

np.float64(64.0)

The loss was even bigger, so we went in the wrong direction with that guess. We make a new guess in the opposite direction: `a = 4`.

**Exercise**: Calculate the loss between the predicted firing rate `y_pred` and the observed firing rate `y_obs` using mean square error. Display the loss.

In [ ]:
x = 2

a = 4 # new guess

y_pred = a * x # Hz
y_obs = 10 # Hz

In [39]:
loss = np.mean((y_pred-y_obs)**2)
loss

np.float64(4.0)

That loss was smaller, so let's make a new guess in the same direction: `a = 5`.

**Exercise**: Calculate the loss between the predicted firing rate `y_pred` and the observed firing rate `y_obs` using mean square error. Display the loss.

In [40]:
x = 2

a = 5 # new guess

y_pred = a * x # Hz
y_obs = 10 # Hz

In [41]:
loss = np.mean((y_pred-y_obs)**2)
loss

np.float64(0.0)

**Demo**: We can write the iterative guessing above using a loop.

In [115]:
x = 2
y_obs = 10 # Hz

for a in [3,2,4,5]:
    y_pred = a * x # Hz
    loss = np.mean((y_pred-y_obs)**2)

    print(f'a: {a}, y_obs: {y_obs}, y_pred: {y_pred}, loss: {loss}')

a: 3, y_obs: 10, y_pred: 6, loss: 16.0
a: 2, y_obs: 10, y_pred: 4, loss: 36.0
a: 4, y_obs: 10, y_pred: 8, loss: 4.0
a: 5, y_obs: 10, y_pred: 10, loss: 0.0


Above, we manually changed the direction of the guess - whether to decrease or increase `a` - based on the loss. But the whole point of machine learning is that the machine should do this automatically.

Gradient descent offers a way to automatically determine which direction to change the parameters in order to minimize the loss. It provides an update rule for the next parameter guess. The update rule for the parameter `a` above is expressed as follows:

$$ a_{next} = a_{current} - \eta \times grad_a$$

where $\eta$ is the learning rate (how much your parameters should change from one guess to the next) and $grad_a$ is the gradient of `a`. The gradient tells us how much the loss will change for a change in the parameter, and the equation for the gradient of parameter `a` can be written as:

$$ grad_a = \frac{\partial{loss}}{\partial{a}} = -2 \times (y_{obs} - y_{pred}) \times x$$

This update of parameter values by calculating the gradient of the loss is what's referred to as "backpropagation".

**Example**: Calculate the gradient of `a` for the loss and the `x` from the first example of the section (provided below). Display the gradient. Based on the update rule for `a`, does a negative gradient suggest that the next `a` should be a bigger or smaller value?

In [121]:
x = 2

a = 3 # initial guess

y_pred = a * x # Hz
y_obs = 10 # Hz

loss = np.mean((y_pred-y_obs)**2)
loss

np.float64(16.0)

In [122]:
grad_a = -2 * (y_obs-y_pred) * x
grad_a

# a negative gradient will cancel out the minus sign in front of the learning rate, so it will lead to a bigger "a" in the next iteration

-16

In the cell below, the `a` is updated using the update rule and the gradient calculated in the example above. Then, the loss is computed for the predicted firing rate given the updated parameter `a`.

**Exercise**: Calculate the next gradient of `a`. Display the gradient. Based on the update rule for `a`, does a this gradient suggest that the next `a` should be a bigger or smaller value?

In [123]:
x = 2

learning_rate = 0.1

a = a - learning_rate * grad_a

y_pred = a * x # Hz
y_obs = 10 # Hz

loss = np.mean((y_pred-y_obs)**2)
print(f'a: {a:.2f}, loss: {loss:.2f}')

a: 4.60, loss: 0.64


In [124]:
grad_a = -2 * (y_obs - y_pred) * x
grad_a 

-3.200000000000003

In the cell below, the `a` is updated again and the loss is calculated for the new prediction with the updated `a`.

**Exercise**: Calculate the next gradient of `a`. Display the gradient. Is the gradient smaller or bigger than in the example? Can you guess what it means if it's smaller/bigger? (Think about the definition of the gradient: How big the change in the loss is for a change in the parameter.)

In [125]:
x = 2

learning_rate = 0.1

a = a - learning_rate * grad_a

y_pred = a * x # Hz
y_obs = 10 # Hz

loss = np.mean((y_pred-y_obs)**2)
print(f'a: {a:.2f}, loss: {loss:.2f}')

a: 4.92, loss: 0.03


In [126]:
grad_a = -2 * (y_obs - y_pred) * x
grad_a 

-0.6400000000000006

Like before, we can put this iterative guessing in a loop so we don't have to write the code and run the cells over and over.



In [ ]:
a = 3 # initial guess
x = 2 # stimulus strength
learning_rate = 0.1

# put the code below in a for loop with 5 iterations

y_pred = a * x # Hz
y_obs = 10 # Hz

loss = np.mean((y_obs-y_pred)**2)

print(f'a: {a:.2f}, y_obs: {y_obs}, y_pred: {y_pred}, loss: {loss:.3f}')

grad_a = -2 * (y_obs-y_pred) * x

a = a - learning_rate * grad_a

a: 3.00, loss: 16.000
a: 4.60, loss: 0.640
a: 4.92, loss: 0.026
a: 4.98, loss: 0.001
a: 5.00, loss: 0.000


In [114]:
a = 3 # initial guess
x = 2
learning_rate = 0.1

# put the code below in a for loop with 5 iterations
for epoch in range(5):
    y_pred = a * x # Hz
    y_obs = 10 # Hz

    loss = np.mean((y_obs-y_pred)**2)
    
    print(f'epoch: {epoch}, a: {a:.2f}, y_obs: {y_obs}, y_pred: {y_pred}, loss: {loss:.3f}')
    
    grad_a = -2 * (y_obs-y_pred) * x

    a = a - learning_rate * grad_a

epoch: 0, a: 3.00, y_obs: 10, y_pred: 6, loss: 16.000
epoch: 1, a: 4.60, y_obs: 10, y_pred: 9.2, loss: 0.640
epoch: 2, a: 4.92, y_obs: 10, y_pred: 9.84, loss: 0.026
epoch: 3, a: 4.98, y_obs: 10, y_pred: 9.968, loss: 0.001
epoch: 4, a: 5.00, y_obs: 10, y_pred: 9.9936, loss: 0.000


## Section 3: Loss in Pytorch

| Code | Description |
| :-- | :-- |
| `model(X_input)` | Pass input `X_input` to a neuronal network `pred`. |
| `y_pred = model(X_input)` | Pass input `X_input` to a neuronal network `pred` and assign the output to a variable `y_net`. |
| `nn.MSELoss()` | Creates a mean squared error (MSE) loss function. |
| `loss_fn = nn.MSELoss()` | Creates a mean squared error (MSE) loss function and assigns it to a variable named `loss_fn`. |
| `nn.MSELoss()(y_pred, y_obs)` | Creates a mean squared error (MSE) loss function. |
| `loss_fn(y_pred, y_obs)` | Uses variable that the loss function is assigned to to calculate the loss between the prediction<br>of the model `y_pred` and the observed y-values from the data `y_obs`. |
| `loss_fn(y_pred, y_obs).item()` | Extracts the loss value as a `float` and from the tensor. |
| `loss = loss_fn(y_pred, y_obs).item()` | Extracts the loss value as a `float` and from the tensor and assigns the output to a variable `loss`. |


**Example**: Create a mean sqare error loss function using PyTorch's `nn` module.

In [ ]:
nn.MSELoss()

MSELoss()

**Exercise**: Create a mean sqare error loss function using PyTorch's `nn` module and assign it to a variable named `loss_fn`. Display the `loss_fn` variable.

In [35]:
loss_fn = nn.MSELoss()
loss_fn

MSELoss()

Run the first cell below to calculate a predicted value `y_pred` for the initial parameter guess `a = 3` and to make both the predicted value and the observed value tensors. Run the second cell to calculate the loss manually (like in the previous section) and print the loss between `y_pred` and `y_obs`.

In [20]:
x = 2
a = 3 # initial guess
y_pred = torch.tensor(a * x)

y_obs = torch.tensor(10, dtype = torch.float32)
y_pred, y_obs

(tensor(6), tensor(10.))

In [30]:
loss = torch.mean((y_pred-y_obs)**2)
print(f'a: {a}, y_obs: {y_obs}, y_pred: {y_pred}, loss: {loss}')

a: 3, y_obs: 10.0, y_pred: 6, loss: 16.0


**Exercise**: Instead of calculating it manually, use the `nn` module's mean square error loss function to calculate the loss between `y_pred` and `y_obs`.

In [31]:
nn.MSELoss()(y_pred, y_obs)

tensor(16.)

**Exercise**: Use the loss function variable `loss_fn` defined below to calculate mean square error loss function to calculate the loss between the `y_pred` and `y_obs`.

In [23]:
loss_fn = nn.MSELoss()

In [32]:
loss_fn(y_pred, y_obs)

tensor(16.)

**Exercise**: Calculate the loss using either of the methods above and extract the **number as a float** from the loss tensor. 

**Hint**: See code reference table.

In [33]:
loss_fn(y_pred, y_obs).item()

16.0

**Exercise**: Calculate the loss using either of the methods above, extract the **number as a float** from the loss tensor, and assign this number to a variable named `loss`. Display the `loss` variable.

In [34]:
loss = loss_fn(y_pred, y_obs).item()
loss

16.0

## Section 4: Different Problems Require Different Kinds of Loss Functions

| Code | Description |
| --- | --- |
| `model(X_input)` | Pass input `X_input` to a neuronal network `model`. |
| `y_model = model(X_input)` | Pass input `X_input` to a neuronal network `model` and assign the output to a variable `y_net`. |
| `nn.MSELoss()` | Creates a mean squared error (MSE) loss function and assigns it to a variable named `loss_function`. Typically used for regression problems. |
| `loss_function = nn.MSELoss()` | Creates a mean squared error (MSE) loss function and assigns it to a variable named `loss_function`. Typically used for regression problems. |
| `loss_function(y_model, y_true)` | Calculates the loss between the output of the network `y_model` and the true y-values from the data `y_true`. |
| `loss_function(y_model, y_true).item()` | Extracts the loss value (the number alone as a ``float`` and not as a ``tensor`` type). |
| `nn.BCELogitsWithLoss()` | Creates a cross-entropy loss function for binary classification problems.|
| `nn.CrossEntropyLoss()` | Creates a cross-entropy loss function for multiclass classification problems.|


## (Extra) Section 5: `torch.tensor()` has Autograd directly implemented, so it can automatically compute deriviates. 

The great thing about PyTorch is that it takes care of the gradient calculation and parameter updates for you, so you don't need to do it manually like you did above. This is particularly useful when you have a big model with a lot of parameters and layers that need to be kept track of and updated. 

```python
x = torch.tensor([2.], requires_grad=True)
y = x ** 2
y.backward()
x.grad  # tensor([7.])
```


| Code | Description |
| :-- | :-- |
| `x = torch.tensor([content_of_tensor], requires_grad=True)` | Create tensor and specify that gradients should be tracked. |
| `x.requires_grad` | Check if gradient tracking is on. |
| `y.backward()` | Do backpropagation on `y`. |
| `x.detach()` | Stop gradient tracking by detaching the tensor from the graph. |
| `with x.no_grad():` | Pause gradient tracking temporarily|
| `x.zero_()` | Reset the gradient. |

**Example**: Create a tensor `f` that contains a scalar ``3.0`` and specify that gradients should be tracked 

In [34]:
f = torch.tensor([3.0], requires_grad=True)
f

tensor([3.], requires_grad=True)

**Exercise**: Create a tensor `g` that contains a scalar ``5.0`` and specify that gradients should be tracked.

In [35]:
g = torch.tensor([5.0], requires_grad=True)
g

tensor([5.], requires_grad=True)

**Exercise**: Check that gradient gradient tracking is on for `g`.

In [36]:
g.requires_grad

True

**Exercise**: Check what `g`'s gradient is. 

**Note**: Since we haven't carried out any operations on `g` yet, it should be empty and nothing will be displayed when you print it.

In [37]:
g.grad

**Exercise**: Run the cell below where `h` is set to `7` times the tensor `g`. No need to change the code.

In [39]:
h = 7 * g
g

tensor([5.], requires_grad=True)

**Exercise**: Do backprogation on `h`.

In [40]:
h.backward()

**Exercise**: Check the gradient of `g` again. This time, it should not be empty. Can you guess why it has this particular value?

**Hint**: Compare the value of `g`'s gradient to the equation where `h` is calculated above.

In [41]:
g.grad

tensor([7.])

**Exercise**: Check the gradient function of `h`. 
If you display it, it should start with `<MulBackward0`. Why does it say "Mul" in the beginning, do you think?

In [42]:
h.grad_fn

**Exercise**: Run the cell below to create the tensor `c` which contains the scalar `6.0` and sets `d = c + 3`. You don't have to change anything in the code.

In [43]:
c = torch.tensor([6.0], requires_grad=True)
d = c + 3
d

tensor([9.], grad_fn=<AddBackward0>)

**Exercise**: Do backpropagation on `d`.

In [44]:
d.backward()

**Exercise**: Check the gradient of `c`.

In [45]:
c.grad

tensor([1.])

**Exercise**: Check the gradient function of `d`. The output should start with `<AddBackward0`. Why does it start with "Add" do you think?

In [46]:
d.grad_fn

**Exercise**: Reset ("zero out") `c`'s gradient.

In [47]:
c.grad.zero_()

tensor([0.])

Below, we find the `a` that fits the data in the equation $y = a * x$, like you did in section 2. But this time, you'll use autograd instead.

**Exercise**: Run the first cell below to initialize the data variables `x`, `a`, and `y_obs`. Then put the code in the **second** cell in a for loop that stops after 5 steps.

In [53]:
# initialize parameters
a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
learning_rate = 0.1

# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0]) # output, no gradient needed


In [ ]:
# forward pass
y_pred = a * x

# calculate the loss
loss = (y_pred - y_obs)**2

print(f"step {step}: a={a.item():.3f}, y_obs={y_obs.item():.2f}, y_pred={y_pred.item():.2f}, loss={loss.item():.3f}")

# backward pass — autograd computes dl/da for us
loss.backward()

# update parameter
with torch.no_grad():
    a -= learning_rate * a.grad

# reset gradient for next step
a.grad.zero_()

step 4: a=1.000, y_obs=10.00, y_pred=2.00, loss=64.000


tensor([0.])

In [ ]:
for step in range(5):

    # forward pass
    y_pred = a * x

    # calculate the loss
    loss = (y_pred - y_obs)**2

    print(f"step {step}: a={a.item():.3f}, y_pred={y_pred.item():.2f}, loss={loss.item():.3f}")

    # backward pass — autograd computes dl/da for us
    loss.backward()

    # update parameter
    with torch.no_grad():
        a -= learning_rate * a.grad

    # reset gradient for next step
    a.grad.zero_()

step 0: a=1.000, y_pred=2.00, loss=64.000
step 1: a=4.200, y_pred=8.40, loss=2.560
step 2: a=4.840, y_pred=9.68, loss=0.102
step 3: a=4.968, y_pred=9.94, loss=0.004
step 4: a=4.994, y_pred=9.99, loss=0.000


#### Derivation of Gradient Equation

We can use the loss to find out how to do better with our next guess. That's where the **gradient** comes in. *The gradient tells us how much the loss changes if we change a parameter in our model.* In our model here, it tells us how much the deviation between our prediction and the observed data `y_obs` will change if we adjust `a`. In mathematical terms, the gradient is the derivative of the loss with respect to the parameter.

The math below shows how the gradient for `a` is derived if you want to know where the final equation comes from, but you can do the next exercise without going through the derivation. We start with definition of the gradient: the change in loss ($`\Delta loss`$) per change in the parameter ($`\Delta a`$).

$$grad_a = \frac{\Delta loss}{\Delta a}$$

When the change in `a` is small, this can be written as a differential equation:

$$grad_a = \frac{\partial{loss}}{\partial{a}}$$

we insert $loss = (y_{obs}-y_{pred})^2$

$$ grad_a = \frac{\partial{(y_{obs}-y_{pred})}}{\partial{a}}$$

we insert $y_{pred} = a \times x$

$$ grad_a = \frac{\partial{(y_{obs}-a \times x)}}{\partial{a}}$$

we calculate the derivative

$$ grad_a = -2(y_{obs}-a \times x) \times x$$

we write $`y_{obs}`$ instead of $`a \times x`$ in the final equation

$$ grad_a = -2(y_{obs}-y_{pred}) \times x$$

Using more mathematical notation with the gradient expressed with $\nabla$ and $\mathcal{L}$ for the loss, we get:

$$ \nabla_a(\mathcal{L}) = -2 \times (y_{obs}-y_{pred}) \times x$$

## Section 4: Autograd is very useful for efficient calculations--way faster and less complicated than doing it yourself!

**Important Note**: Autograd is not actually faster for small toy data examples because of the overhead in setting up the computational graph, creating tensors etc. Should I make this a separate notebook and make it a google collab thing? Should things in session 01 be on google collab because of gpu/cpu?

In [1]:
import time

In [2]:
# initialize parameters
a = 1.0
learning_rate = 0.1

# data
x = 2.0
y_obs = 10.0

In [ ]:
start = time.perf_counter()

for step in range(100000):
    # Forward pass
    y_pred = a * x

    # calculate loss
    loss = (y_pred - y_obs)**2

    # Compute gradient
    grad_a = 2 * (y_pred - y_obs) * x

    # Update the parameter
    a = a - learning_rate * grad_a

end = time.perf_counter()

print(f"Time without autograd: {end-start:.4f} seconds")

Time without autograd: 0.0018 seconds


In [ ]:
# initialize parameters
a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
learning_rate = 0.1

# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True) # output, gradient needed

In [ ]:
start = time.perf_counter()
for step in range(5):
    # Forward pass
    y_pred = a * x
    loss = (y_pred - y_obs)**2

    # Backward pass — autograd computes dl/da for us
    loss.backward()

    # Update parameter
    with torch.no_grad():
        a -= learning_rate * a.grad

    # Reset gradient for next step
    a.grad.zero_()
end = time.perf_counter()

print(f"Time with autograd: {end-start:.4f} seconds")

Time with autograd: 0.0067 seconds


In [40]:
import timeit

In [48]:
# data
x = 2.0
y_obs = 10.0
def train_without_autograd():
    # initialize parameters
    a = 1.0
    learning_rate = 0.1
    for step in range(5):
        # Forward pass
        y_pred = a * x

        # calculate loss
        loss = (y_pred - y_obs)**2

        # Compute gradient
        grad_a = 2 * (y_pred - y_obs) * x

        # Update the parameter
        a = a - learning_rate * grad_a
    
time_without = timeit.timeit(train_without_autograd, number = 10)
print(f"Without autograd: {time_without:.5f} seconds")

Without autograd: 0.00004 seconds


In [ ]:
# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True) # output, gradient needed

def train_with_autograd():
    # initialize parameters
    a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
    learning_rate = 0.1
    for step in range(5):
        # Forward pass
        y_pred = a * x
        loss = (y_pred - y_obs)**2

        # Backward pass — autograd computes dl/da for us
        loss.backward()

        # Update parameter
        with torch.no_grad():
            a -= learning_rate * a.grad

        # Reset gradient for next step
        a.grad.zero_()

time_with = timeit.timeit(train_with_autograd, number=10)
print(f"With autograd: {time_with:.5f} seconds")

With autograd: 0.01088 seconds


## Leftover accuracy section (to be moved)

The output of the network is a score for each class that reflects the networks belief that a data point corresponds to a given class. This is not the same as a class label. To get the output in the form of a class guess by the network, we have to determine which class the network thinks that a data point is most likely to belong to using the output scores.

| Code | Description |
| --- | --- |
| `torch.argmax(x, dim=1)` | Finds the index at which the tensor `x` has the highest value along its first dimension. |
| `a == b` | Compares each element of the tensors (or arrays) `a` and `b` and returns a tensor of boolean (`True` or `False`) values indicating which elements are the same (`True`) and different (`False`). |
| `(a == b).sum()` or `torch.sum(a == b)`| Sums all elements where the condition `a == b` is `True`. `True` is counted as 1, `False` as 0. |
| `(a == b).sum() / len(a)` | Calculates proportion of elements in `a` where the element is equal to the corresponding element in `b`.|

Run the cell below to create a network, select a subset of the data, and pass this subset through the network to get an output `y_net`.