## Setup

### Import Libraries

In [1]:
import torch

## Section 1: Machine Learning is iterative guessing.  Iteration can be done with For Loops.

When you train a neural network, you're making the model guess what the output should be over and over again. Between each guess, the model parameters are updated until the guess is good enough. In other words, it's an iterative improvement of the model. This iteration can be programmed with a for loop. A for loop lets us perform an operation a predefined number of times and is an incredibly useful programming concept. In this section, you will get som practice writing for loops.

| Code | Description |
| --- | --- |
| `for letter in ["a", "b", "c"]:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(letter)` | Print every `letter` in the list `["a", "b", "c"]`|
| `for i in range(5):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every number `i` between 0 and 5 (not including 5)|
| `for i in range(2, 7):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every number `i` between 2 and 7 (not including 7)|
| `for i in range(1, 10, 2):` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(i)` | Print every **second** number `i` between 1 and 10 (not including 10)|
| `for x_i in x:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `print(x_i)` | Print every element `x_i` in the collection `x`|
| `for x_i in x:` <br> &nbsp;&nbsp;&nbsp;&nbsp; `for y_i in y`: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `print(x_i, y_i)` | Print every element `x_i` and `y_i` in the collections `x` and `y`|
| `new_list = []` or `new_list = list()`| Initialize an empty list named `new_list` |
| `new_list.append(element)`| Append an element to the list `new_list` |

#### **Exercises**

**Example**: Write a for loop that prints the numbers **0** to **9**.

In [3]:
for num in range(9):
    print(num)

0
1
2
3
4
5
6
7
8


**Exercise**: Write a for loop that prints the numbers **5** to **10**.


In [4]:
for i in range(5,10):
    print(i)

5
6
7
8
9


**Exercise**: Write a for loop that counts from **0** to **100** in steps of **10**.

In [5]:
for j in range(0,100,10):
    print(j)

0
10
20
30
40
50
60
70
80
90


**Exercise**: Nested loops: Use loops to print all `fruits` and `colors`, for example `banana is yellow"`.

In [6]:
# provided

fruits = ["banana", "orange", "cherry"]
colors= ["yellow", "orange", "green"];

In [7]:
for fruit in fruits:
    for color in colors:
        print(fruit+' is '+color)

banana is yellow
banana is orange
banana is green
orange is yellow
orange is orange
orange is green
cherry is yellow
cherry is orange
cherry is green


**Exercise**: Write a loop that calculates the square of each element in `numbers` and stores the result in a new list called `squared_numbers`. Display the `squared_numbers` list at the end to check that it is correct.

In [8]:
numbers = [4, 6, 12, 50]

In [9]:
squared_numbers = []

for i in range(len(numbers)):
    num_squared = numbers[i]**2
    squared_numbers.append(num_squared)

squared_numbers

[16, 36, 144, 2500]

**Exercise**: Write a loop that multiplies each element in the list `numbers` by 4 and store the results in a new list called `multiplied_numbers`. Display `multiplied_numbers` to check that it is correct.

In [10]:
numbers = [4, 6, 12, 50]

In [11]:
multiplied_numbers = []
for num in numbers:
    mult_number = 4*num

    multiplied_numbers.append(mult_number)

multiplied_numbers

[16, 24, 48, 200]

## Section 2: Machine Learning is Adjusting Guesses Based on Error. 

| Code | Description |
| --- | --- |
| `param = param - learning_rate * gradient * param` | Update the parameter `param`. |
| `z**2` | Calculate the square of z. |
| `y_pred = a * x` | Make a prediction using parameter `a` and input `x`. |
| `(y_pred - y_obs)**2` | Calculate the squared error (loss) between prediction and observation. |
| `grad_a = -2 * (y_obs - y_pred) * x` | Calculate the gradient of the loss with respect to parameter `a`. |
| `a = a - learning_rate * grad_a` | Update parameter `a` using the gradient and learning rate. |
| `learning_rate = some_num` | Define the learning rate hyperparameter, which controls the step size of gradient descent. |

Let's suppose we have some recorded data that we know can be described by a function of the form:

$$y = a \times x$$

However, we don't know the value of `a`. We could of course use one of the standard linear regression functions that many python libraries offer to do this, but let's do it with machine learning instead. And we'll do it manually to get a better intuition for what is actually going on under the hood in machine learning.

To keep it simple, say we have a single observation  `y_obs = 10.0` recorded at `x = 2.0`. In the cell below, we start with an initial guess `a = 1.0`. Run the cell to see how close the prediction `y_pred` is to the observed `y_obs` with this initial guess for `a`.

In [13]:
# Data
x = 2.0
y_obs = 10.0

# Parameter
a = 1.0 # initial guess

y_pred = a * x
print(f"Intial guess a = {a}; observed y = {y_obs}, predicted y = {y_pred}, difference = {y_obs-y_pred}")

Intial guess a = 1.0; observed y = 10.0, predicted y = 2.0, difference = 8.0


The predicted `y_pred` wasn't very close to our observed `y_obs`. The deviation between the prediction and the observed data is referred to as the "loss" in the machine learning context. A common way to quantify the loss is to calculate the squared difference between the observed and the predicted value.

**Exercise**: Calculate the squared difference between `y_pred` and `y_obs`.

In [14]:
(y_pred - y_obs)**2

64.0

We can use the loss to find out how to do better with our next guess. That's where the **gradient** comes in. *The gradient tells us how much the loss changes if we change a parameter in our model.* In our model here, it tells us how much the deviation between our prediction and the observed data `y_obs` will change if we adjust `a`. In mathematical terms, the gradient is the derivative of the loss with respect to the parameter.

The math below shows how the gradient for `a` is derived if you want to know where the final equation comes from, but you can do the next exercise without going through the derivation. We start with definition of the gradient: the change in loss ($`\Delta loss`$) per change in the parameter ($`\Delta a`$).

$$grad_a = \frac{\Delta loss}{\Delta a}$$

When the change in `a` is small, this can be written as a differential equation:

$$grad_a = \frac{\partial{loss}}{\partial{a}}$$

we insert $loss = (y_{obs}-y_{pred})^2$

$$ grad_a = \frac{\partial{(y_{obs}-y_{pred})}}{\partial{a}}$$

we insert $y_{pred} = a \times x$

$$ grad_a = \frac{\partial{(y_{obs}-a \times x)}}{\partial{a}}$$

we calculate the derivative

$$ grad_a = -2(y_{obs}-a \times x) \times x$$

we write $`y_{obs}`$ instead of $`a \times x`$ in the final equation

$$ grad_a = -2(y_{obs}-y_{pred}) \times x$$

**Exercise**: Write the **last** equation above in code.


In [15]:
grad_a = -2*(y_obs-y_pred)*x
grad_a

-32.0

We'll now use the gradient we calculated to update the parameter `a` before our next guess.

**Exercise**: Calculate a new parameter value `a_new` using the current value of `a` and the gradient calculated above.

**Hint**: Check the reference table to see how parameters can be updated using the gradient.

In [16]:
a = a-grad_a*a
a

33.0

Now we're ready to make our next guess. 

**Exercise**: Calculate `y_pred` again but use the new parameter value `a_new` instead of the original `a`.

**Note**: This guess will actually be worse than the initial guess, so don't worry, that's to be expected.

In [17]:
y_pred = a * x
y_pred

66.0

There is an important *hyperparameter* (different from a regular parameter) called the **learning rate**, which determines how we learn in machine learning. Without an appropriate learning rate, the updated parameter values won't give us better predictions. The lack of an appropriate learning rate is the reason why our second guess was worse than the first guess above. The learning rate is multiplied with the gradient and the current parameter value in the parameter update.

**Exercise**: Calculate the updated parameter value `a` again, but this time, multiply the gradient and the current parameter value with the `learning_rate` defined in the cell below.

In [24]:
a = 1
learning_rate = 0.1

In [25]:
a = a-learning_rate*grad_a*a
a

4.2

**Exercise**: Calculate `y_pred` with the `a` that we have now. Are we closer to or further away from the observed `y_obs` this time?

In [26]:
y_pred = a*x
y_pred

8.4

**Exercise**: The code in the second below contains all the steps we did above that go into updating the parameter. Put the steps in a for loop that stops after 5 iterations. Was the final value of `a` what you expected?

In [32]:
a = 1 # start with initial guess a = 1 again

In [33]:
# forward pass
y_pred = a * x

# calculate loss
loss = (y_pred - y_obs)**2

print(f"a={a:.3f}, y_pred={y_pred:.2f}, loss={loss:.3f}")

# compute gradient
grad_a = 2 * (y_pred - y_obs) * x

# update the parameter
a = a - learning_rate * grad_a

a=1.000, y_pred=2.00, loss=64.000


In [30]:
for step in range(5):
    # Forward pass
    y_pred = a * x

    # calculate loss
    loss = (y_pred - y_obs)**2

    print(f"a={a:.3f}, y_pred={y_pred:.2f}, loss={loss:.3f}")

    # Compute gradient
    grad_a = 2 * (y_pred - y_obs) * x

    # Update the parameter
    a = a - learning_rate * grad_a

a=5.000, y_pred=10.00, loss=0.000
a=5.000, y_pred=10.00, loss=0.000
a=5.000, y_pred=10.00, loss=0.000
a=5.000, y_pred=10.00, loss=0.000
a=5.000, y_pred=10.00, loss=0.000


## Section 3: `torch.tensor()` has Autograd directly implemented, so it can automatically compute deriviates. 

The great thing about PyTorch is that it takes care of the gradient calculation and parameter updates for you, so you don't need to do it manually like you did above. This is particularly useful when you have a big model with a lot of parameters and layers that need to be kept track of and updated. 

```python
x = torch.tensor([2.], requires_grad=True)
y = x ** 2
y.backward()
x.grad  # tensor([7.])
```


| Code | Description |
| :-- | :-- |
| `x = torch.tensor([content_of_tensor], requires_grad=True)` | Create tensor and specify that gradients should be tracked. |
| `x.requires_grad` | Check if gradient tracking is on. |
| `y.backward()` | Do backpropagation on `y`. |
| `x.detach()` | Stop gradient tracking by detaching the tensor from the graph. |
| `with x.no_grad():` | Pause gradient tracking temporarily|
| `x.zero_()` | Reset the gradient. |

**Example**: Create a tensor `f` that contains a scalar ``3.0`` and specify that gradients should be tracked 

In [34]:
f = torch.tensor([3.0], requires_grad=True)
f

tensor([3.], requires_grad=True)

**Exercise**: Create a tensor `g` that contains a scalar ``5.0`` and specify that gradients should be tracked.

In [35]:
g = torch.tensor([5.0], requires_grad=True)
g

tensor([5.], requires_grad=True)

**Exercise**: Check that gradient gradient tracking is on for `g`.

In [36]:
g.requires_grad

True

**Exercise**: Check what `g`'s gradient is. 

**Note**: Since we haven't carried out any operations on `g` yet, it should be empty and nothing will be displayed when you print it.

In [37]:
g.grad

**Exercise**: Run the cell below where `h` is set to `7` times the tensor `g`. No need to change the code.

In [39]:
h = 7 * g
g

tensor([5.], requires_grad=True)

**Exercise**: Do backprogation on `h`.

In [40]:
h.backward()

**Exercise**: Check the gradient of `g` again. This time, it should not be empty. Can you guess why it has this particular value?

**Hint**: Compare the value of `g`'s gradient to the equation where `h` is calculated above.

In [41]:
g.grad

tensor([7.])

**Exercise**: Check the gradient function of `h`. 
If you display it, it should start with `<MulBackward0`. Why does it say "Mul" in the beginning, do you think?

In [42]:
h.grad_fn

**Exercise**: Run the cell below to create the tensor `c` which contains the scalar `6.0` and sets `d = c + 3`. You don't have to change anything in the code.

In [43]:
c = torch.tensor([6.0], requires_grad=True)
d = c + 3
d

tensor([9.], grad_fn=<AddBackward0>)

**Exercise**: Do backpropagation on `d`.

In [44]:
d.backward()

**Exercise**: Check the gradient of `c`.

In [45]:
c.grad

tensor([1.])

**Exercise**: Check the gradient function of `d`. The output should start with `<AddBackward0`. Why does it start with "Add" do you think?

In [46]:
d.grad_fn

**Exercise**: Reset ("zero out") `c`'s gradient.

In [47]:
c.grad.zero_()

tensor([0.])

Below, we find the `a` that fits the data in the equation $y = a * x$, like you did in section 2. But this time, you'll use autograd instead.

**Exercise**: Run the first cell below to initialize the data variables `x`, `a`, and `y_obs`. Then put the code in the **second** cell in a for loop that stops after 5 steps.

In [53]:
# initialize parameters
a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
learning_rate = 0.1

# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0]) # output, no gradient needed


In [ ]:
# forward pass
y_pred = a * x

# calculate the loss
loss = (y_pred - y_obs)**2

print(f"step {step}: a={a.item():.3f}, y_obs={y_obs.item():.2f}, y_pred={y_pred.item():.2f}, loss={loss.item():.3f}")

# backward pass — autograd computes dl/da for us
loss.backward()

# update parameter
with torch.no_grad():
    a -= learning_rate * a.grad

# reset gradient for next step
a.grad.zero_()

step 4: a=1.000, y_obs=10.00, y_pred=2.00, loss=64.000


tensor([0.])

In [ ]:
for step in range(5):

    # forward pass
    y_pred = a * x

    # calculate the loss
    loss = (y_pred - y_obs)**2

    print(f"step {step}: a={a.item():.3f}, y_pred={y_pred.item():.2f}, loss={loss.item():.3f}")

    # backward pass — autograd computes dl/da for us
    loss.backward()

    # update parameter
    with torch.no_grad():
        a -= learning_rate * a.grad

    # reset gradient for next step
    a.grad.zero_()

step 0: a=1.000, y_pred=2.00, loss=64.000
step 1: a=4.200, y_pred=8.40, loss=2.560
step 2: a=4.840, y_pred=9.68, loss=0.102
step 3: a=4.968, y_pred=9.94, loss=0.004
step 4: a=4.994, y_pred=9.99, loss=0.000


## Section 4: Autograd is very useful for efficient calculations--way faster and less complicated than doing it yourself!

**Important Note**: Autograd is not actually faster for small toy data examples because of the overhead in setting up the computational graph, creating tensors etc. Should I make this a separate notebook and make it a google collab thing? Should things in session 01 be on google collab because of gpu/cpu?

In [1]:
import time

In [2]:
# initialize parameters
a = 1.0
learning_rate = 0.1

# data
x = 2.0
y_obs = 10.0

In [ ]:
start = time.perf_counter()

for step in range(100000):
    # Forward pass
    y_pred = a * x

    # calculate loss
    loss = (y_pred - y_obs)**2

    # Compute gradient
    grad_a = 2 * (y_pred - y_obs) * x

    # Update the parameter
    a = a - learning_rate * grad_a

end = time.perf_counter()

print(f"Time without autograd: {end-start:.4f} seconds")

Time without autograd: 0.0018 seconds


In [ ]:
# initialize parameters
a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
learning_rate = 0.1

# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True) # output, gradient needed

In [ ]:
start = time.perf_counter()
for step in range(5):
    # Forward pass
    y_pred = a * x
    loss = (y_pred - y_obs)**2

    # Backward pass — autograd computes dl/da for us
    loss.backward()

    # Update parameter
    with torch.no_grad():
        a -= learning_rate * a.grad

    # Reset gradient for next step
    a.grad.zero_()
end = time.perf_counter()

print(f"Time with autograd: {end-start:.4f} seconds")

Time with autograd: 0.0067 seconds


In [40]:
import timeit

In [48]:
# data
x = 2.0
y_obs = 10.0
def train_without_autograd():
    # initialize parameters
    a = 1.0
    learning_rate = 0.1
    for step in range(5):
        # Forward pass
        y_pred = a * x

        # calculate loss
        loss = (y_pred - y_obs)**2

        # Compute gradient
        grad_a = 2 * (y_pred - y_obs) * x

        # Update the parameter
        a = a - learning_rate * grad_a
    
time_without = timeit.timeit(train_without_autograd, number = 10)
print(f"Without autograd: {time_without:.5f} seconds")

Without autograd: 0.00004 seconds


In [ ]:
# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True) # output, gradient needed

def train_with_autograd():
    # initialize parameters
    a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
    learning_rate = 0.1
    for step in range(5):
        # Forward pass
        y_pred = a * x
        loss = (y_pred - y_obs)**2

        # Backward pass — autograd computes dl/da for us
        loss.backward()

        # Update parameter
        with torch.no_grad():
            a -= learning_rate * a.grad

        # Reset gradient for next step
        a.grad.zero_()

time_with = timeit.timeit(train_with_autograd, number=10)
print(f"With autograd: {time_with:.5f} seconds")

With autograd: 0.01088 seconds


## Leftover accuracy section (to be moved)

The output of the network is a score for each class that reflects the networks belief that a data point corresponds to a given class. This is not the same as a class label. To get the output in the form of a class guess by the network, we have to determine which class the network thinks that a data point is most likely to belong to using the output scores.

| Code | Description |
| --- | --- |
| `torch.argmax(x, dim=1)` | Finds the index at which the tensor `x` has the highest value along its first dimension. |
| `a == b` | Compares each element of the tensors (or arrays) `a` and `b` and returns a tensor of boolean (`True` or `False`) values indicating which elements are the same (`True`) and different (`False`). |
| `(a == b).sum()` or `torch.sum(a == b)`| Sums all elements where the condition `a == b` is `True`. `True` is counted as 1, `False` as 0. |
| `(a == b).sum() / len(a)` | Calculates proportion of elements in `a` where the element is equal to the corresponding element in `b`.|

Run the cell below to create a network, select a subset of the data, and pass this subset through the network to get an output `y_net`.