## Setup

### Import Libraries

In [1]:
import torch

## Section 1: `torch.tensor()` works like `np.array()`
| Code | Description |
|------------------------------------|------------------------------------|
| `torch.tensor(2)` | Creates a tensor containing the scalar value 2. |
| `torch.tensor([0,1,2])` | Creates a tensor containing the vector with values 0, 1, and 2. |
| `torch.tensor([[1,2,3], [4,5,6]])` | Creates a 2-dimensional tensor of size 2x3 containing the values from 1 to 6. |
| `torch.linspace(0,5,11)` | Initializes a 1D tensor with the numbers from 0 to 5 with 0.5 spacing. |
| `torch.matmul(A,B)` | Performs matrix multiplication on the two tensors A and B. |
| `x = torch.tensor(2)` <br> `float(x)` | Turn torch tensor containing scalar into float number. |
| `x = torch.tensor(2.4)` <br> `x.item()` | Get value of tensor as standard Python number (the type is automatically recognized). |



<span class="theorem-title">**Example 1**</span> Create a tensor of the
scalar value 10.

In [ ]:
torch.tensor(10)

tensor(10)

In [ ]:
A = torch.tensor([[1,2], [3,4], [5,6]])
B = torch.tensor([[7,8,9], [10,11,12]])
torch.matmul(A,B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.tensor([5])
float(x)

5.0

In [5]:
x = torch.tensor([2.44, 2.1])
x = x.numpy()
x

array([2.44, 2.1 ], dtype=float32)

## Section 2: ...and also, it can run off of GPUs

| Code | Description |
|------------------------------------|------------------------------------|
| `x.device` | where is the tensor stored? |
| `torch.cuda.is_available()` | Is a GPU available? |
| `torch.cuda.device_count()` | Number of GPUs  |
| `torch.cuda.get_device_name()` | Name of GPUs (if any) |
| --- | --- |
| `x = torch.tensor([1, 2, 3], devicde='cuda')` | Create a tensor on the GPU |
| `x_cpu = x.to('cpu')` | Copy it to the CPU. |
| `x_gpu = x_cpu.to('cuda')` | Copy it to the GPU. |

<span class="theorem-title">**Example 3**</span> Convert the tensor
object of the scalar number 5 into a float object.

## Section 4: And it has Autograd directly implmented, so it can compute deriviates!

ChatGPT's explanation:  https://chatgpt.com/s/t_693ac08bc9ac8191a5218a73d6ef832d


```python
x = torch.tensor([2.], requires_grad=True)
y = x ** 2
y.backward()
x.grad  # tensor([7.])
```


| Code | Description |
| :-- | :-- |
| `x.requires_grad` | Is gradient tracking on? |
| `x.detach()` | Stop gradient tracking |
| `with x.no_grad():` | Pause gradient tracking temporarily|
| `x.zero_()` | Reset the gradient. |


aa

In [10]:
import torch

x = torch.tensor([2.], requires_grad=True)
y = x * 5 + 1
y.backward()
x.grad  

tensor([5.])

## Section 4: ...and it's fully-compatible with Numpy

| Code | Description |
|------------------------------------|------------------------------------|
| `x = torch.tensor([1, 2, 3])` <br> `x.numpy()` | Returns content of tensor as numpy array. |