<a target="_blank" href="https://colab.research.google.com/github/atleer/intro-to-deep-learning-dev/blob/main/Day01/01_intro_to_pytorch/01_pytorch_fundamentals_for_colab.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Setup

### Import Libraries

In [ ]:
import time
import torch
import numpy as np

## Section 1: `torch.tensor()` works like numpy arrays

PyTorch's fundamental data structure is the tensor, which works similarly to NumPy arrays. Tensors can hold scalars, vectors, matrices, or higher-dimensional data. You can create them directly from Python lists, generate sequences with `torch.linspace`, and initialize them as zeros or ones.

| Code | Description |
| :-- | :-- |
| `torch.tensor(2)` | Creates a tensor containing the scalar value 2. |
| `torch.tensor([0,1,2])` | Creates a tensor containing the vector with values 0, 1, and 2. |
| `torch.tensor([[1,2,3], [4,5,6]])` | Creates a 2-dimensional tensor of size 2x3 containing the values from 1 to 6. |
| `torch.linspace(0,5,11)` | Initializes a 1D tensor with the numbers from 0 to 5 with 0.5 spacing. |
| `torch.zeros(5)` | Initializes a 1D tensor of size 5 filled with zeros. |
| `torch.zeros(2,3)` | Initializes a 2D tensor of dimensions 2x3 filled with zeros. |
| `torch.ones(5)` | Initializes a 1D tensor of size filled with ones. |
| `x.shape` | Get the shape of the tensor. |
| `x.reshape(2, 3)` | Reshape the tensor to a new shape. |

**Example**: Create a tensor of the scalar value 10.

In [ ]:
torch.tensor(10)

tensor(10)

**Exercise**: Create a tensor containing the vector with values 1, 2, 3, 4, and 5.

In [ ]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

**Exercise**: Create a 2-dimensional tensor of size 3x2 containing the values 1, 2, 3, 4, 5, and 6.

In [ ]:
torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

**Exercise**: Create a tensor `x` with values 1 through 6 and check its shape using `.shape`.

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x.shape

torch.Size([6])

**Exercise**: Reshape the tensor `x` from above into a 2x3 matrix using `.reshape()`.

In [ ]:
x.reshape(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

**Exercise**: Create a 1D tensor of size 5 filled with zeros using `torch.zeros()`.

In [ ]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

**Exercise**: Create a 2D tensor of dimensions 2x3 filled with zeros using `torch.zeros()`.

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

**Exercise**: Create a 1D tensor of size 5 filled with ones using `torch.ones()`.

In [ ]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

**Exercise**: Use `torch.linspace` to create a 1D tensor with 5 evenly spaced numbers from 0 to 10.

In [ ]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

## Section 2: Tensors are Fully Compatible with NumPy and Mathematical Operations are Done the Same Way

PyTorch tensors can easily be converted to and from NumPy arrays, making it simple to use PyTorch alongside existing NumPy code. Many NumPy-style operations work directly on tensors, such as indexing, slicing, and common mathematical functions.

| Code | Description |
| :-- | :-- |
| `x.numpy()` | Convert a tensor to a NumPy array. |
| `torch.tensor(arr)` | Convert a NumPy array to a tensor. |
| `torch.from_numpy(arr)` | Convert a NumPy array to a tensor (shares memory with the original array). |
| `x = torch.tensor(2)` <br> `float(x)` | Turn torch tensor containing scalar into float number. |
| `x = torch.tensor(2.4)` <br> `x.item()` | Get value of tensor as standard Python number (the type is automatically recognized). |
| `x.sum()` | Sum all elements in the tensor. |
| `x.mean()` | Calculate the mean of all elements. |
| `x[0]` | Index the first element. |
| `x[1:3]` | Slice elements from index 1 to 2. |
| `torch.matmul(A,B)` | Performs matrix multiplication on the two tensors A and B. |

**Example**: Create a tensor `x` containing the values 10, 20, 30 and convert it to a NumPy array using `.numpy()`.

In [ ]:
x = torch.tensor([10, 20, 30])

In [ ]:
x.numpy()

array([10, 20, 30])

**Exercise**: Create a NumPy array and convert it to a PyTorch tensor using `torch.tensor()`.

In [ ]:
arr = np.array([1.5, 2.5, 3.5])

In [ ]:
torch.tensor(arr)

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64)

**Exercise**: Create a NumPy array and convert it to a tensor using `torch.from_numpy()`. This method shares memory with the original array, so changes to one will affect the other.

In [ ]:
arr = np.array([1.0, 2.0, 3.0])

In [ ]:
torch.from_numpy(arr)

tensor([1., 2., 3.], dtype=torch.float64)

**Exercise**: Use `.item()` to get the value of the tensor `x` below as a standard Python number.

In [ ]:
x = torch.tensor(3.14)

In [ ]:
x.item()

3.140000104904175

**Exercise**: Convert the tensor object of the scalar number 5 into a float object.

In [ ]:
x = torch.tensor([5])
x

tensor([5])

In [ ]:
float(x)

5.0

**Exercise**: Calculate the sum of all elements in tensor `x`.

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

In [ ]:
x.sum()

tensor(10.)

**Exercise**: Calculate the mean of all elements in tensor `y` below.

In [ ]:
y = torch.tensor([2.0, 4.0, 6.0, 8.0])

In [ ]:
y.mean()

tensor(5.)

**Exercise**: Index the first element of tensor `y` using `[0]`.

In [ ]:
y[0]

tensor(2.)

**Exercise**: Slice elements from index 1 to 3 (not including 3) from tensor `y` using `[1:3]`.

In [ ]:
y[1:3]

tensor([4., 6.])

**Exercise**: Multiply tensor A with tensor B.

In [ ]:
A = torch.tensor([[1,2], [3,4], [5,6]])
B = torch.tensor([[7,8,9], [10,11,12]])

In [ ]:
torch.matmul(A,B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Section 3: Torch Tensors can Run Off of GPUs

One of PyTorch's key advantages over NumPy is its ability to run computations on GPUs, which can dramatically speed up neural network training. You can check if a GPU is available, move tensors between CPU and GPU, or create tensors directly on the GPU.

| Code | Description |
| :-- | :--|
| `x.device` | where is the tensor stored? |
| `torch.cuda.is_available()` | Is a GPU available? |
| `torch.cuda.device_count()` | Number of GPUs  |
| `torch.cuda.get_device_name()` | Name of GPUs (if any) |
| `x = torch.tensor([1, 2, 3], device='cuda')` | Create a tensor on the GPU |
| `x_cpu = x.to('cpu')` | Copy it to the CPU. |
| `x_gpu = x_cpu.to('cuda')` | Copy it to the GPU. |

This section should be done in Google Colab. Open the notebook in Google Colab by clicking the button below.

<a target="_blank" href="https://colab.research.google.com/github/atleer/intro-to-deep-learning-dev/blob/main/Day01/01_intro_to_pytorch/01_pytorch_fundamentals_for_colab.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**Example**: Check if a GPU is available on your machine using `torch.cuda.is_available()`.

In [ ]:
import torch
torch.cuda.is_available()

False

**Exercise**: Click on "Runtime" in the toolbar, then "Change runtime type", select "T4 GPU" and click "Save". The session is restarted when you change the runtime type, so run the first cell to import the libraries again. Then, check if a GPU is available on your machine. What is the output now?


In [2]:
import time
import torch
import numpy as np

In [ ]:
torch.cuda.is_available()

True

**Exercise**: Check how many GPUs are available using `torch.cuda.device_count()`.

In [ ]:
torch.cuda.device_count()

1

**Exercise**: If a GPU is available, get the name of the GPU using `torch.cuda.get_device_name()`. If no GPU is available, this cell will produce an error.

In [ ]:
torch.cuda.get_device_name()

'Tesla T4'

**Exercise**: Create a tensor `x` containing the values 1, 2, 3 and check which device it is stored on using `.device`.

In [ ]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

**Exercise**: If a GPU is available, move the tensor `x` to the GPU using `.to('cuda')`. If no GPU is available, this cell will produce an error.

In [ ]:
x_gpu = x.to('cuda')
x_gpu.device

device(type='cuda', index=0)

**Exercise**: Create a tensor directly on the GPU by specifying `device='cuda'` in `torch.tensor()`. If no GPU is available, this cell will produce an error.

In [ ]:
y = torch.tensor([4, 5, 6], device='cuda')
y.device

device(type='cuda', index=0)

**Exercise**: Move the tensor `y` created above back to the CPU using `.to('cpu')`.

In [ ]:
y_cpu = y.to('cpu')
y_cpu.device

device(type='cpu')

## Section 4: `torch.tensor()` has Autograd directly implemented, so it can automatically compute deriviates.

Computing derivatives is a fundamental part of so-called gradient descent, which is what makes machine learning so powerful. PyTorch can automatically compute gradients for you, so you don't have to do it manually yourself.

```python
x = torch.tensor([2.], requires_grad=True)
y = x ** 2
y.backward()
x.grad  # tensor([4.])
```

| Code | Description |
| :-- | :-- |
| `x = torch.tensor([content_of_tensor], requires_grad=True)` | Create tensor and specify that gradients should be tracked. |
| `x.requires_grad` | Check if gradient tracking is on. |
| `y.backward()` | Do backpropagation on `y`. |
| `x.detach()` | Stop gradient tracking by detaching the tensor from the graph. |
| `with x.no_grad():` | Pause gradient tracking temporarily|
| `x.zero_()` | Reset the gradient. |

**Example**: Create a tensor `f` that contains a scalar ``3.0`` and specify that gradients should be tracked

In [ ]:
f = torch.tensor([3.0], requires_grad=True)
f

tensor([3.], requires_grad=True)

**Exercise**: Create a tensor `g` that contains a scalar ``5.0`` and specify that gradients should be tracked.

In [ ]:
g = torch.tensor([5.0], requires_grad=True)
g

tensor([5.], requires_grad=True)

**Exercise**: Check that gradient gradient tracking is on for `g`.

In [ ]:
g.requires_grad

True

**Exercise**: Check what `g`'s gradient is.

**Note**: Since we haven't carried out any operations on `g` yet, it should be empty and nothing will be displayed when you print it.

In [ ]:
g.grad

**Exercise**: Run the cell below where `h` is set to `7` times the tensor `g`. No need to change the code.

In [ ]:
h = 7 * g
g

tensor([5.], requires_grad=True)

**Exercise**: Do backprogation on `h`. This calculates the gradient of `g`.

In [ ]:
h.backward()

**Exercise**: Check the gradient of `g` again. This time, it should not be empty. Can you guess why it has this particular value?

**Hint**: Compare the value of `g`'s gradient to the equation where `h` is calculated above.

In [ ]:
g.grad

tensor([7.])

**Exercise**: Check the gradient function of `h`.
If you display it, it should start with `<MulBackward0`. Why does it say "Mul" in the beginning, do you think?

In [ ]:
h.grad_fn

**Exercise**: Run the cell below to create the tensor `c` which contains the scalar `6.0` and sets `d = c + 3`. You don't have to change anything in the code.

In [ ]:
c = torch.tensor([6.0], requires_grad=True)
d = c + 3
d

tensor([9.], grad_fn=<AddBackward0>)

**Exercise**: Do backpropagation on `d`.

In [ ]:
d.backward()

**Exercise**: Check the gradient of `c`.

In [ ]:
c.grad

tensor([1.])

**Exercise**: Check the gradient function of `d`. The output should start with `<AddBackward0`. Why does it start with "Add" do you think?

In [ ]:
d.grad_fn

**Exercise**: Reset ("zero out") `c`'s gradient.

In [ ]:
c.grad.zero_()

tensor([0.])

## (Extra, Demo) Section 5: PyTorch is very useful for efficient calculations

In [ ]:
# Check if GPU is available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

Using device: cuda


In [ ]:
# Large matrix multiplication comparison
size = 500  # smaller size for pure Python (it's VERY slow)

# Create large random matrices with NumPy
A_np = np.random.randn(size, size).astype(np.float32)
B_np = np.random.randn(size, size).astype(np.float32)

# Time pure Python (nested loops) - this is painfully slow!
A_list = A_np.tolist()
B_list = B_np.tolist()

start = time.perf_counter()
C_python = [[sum(A_list[i][k] * B_list[k][j] for k in range(size))
             for j in range(size)] for i in range(size)]
python_time = time.perf_counter() - start

print(f"Matrix multiplication ({size}x{size}):")
print(f"  Pure Python:   {python_time:.4f} seconds")

# Time NumPy (CPU)
start = time.perf_counter()
C_np = np.matmul(A_np, B_np)
numpy_time = time.perf_counter() - start
print(f"  NumPy (CPU):   {numpy_time:.4f} seconds")

# Time PyTorch CPU
A_cpu = torch.from_numpy(A_np)
B_cpu = torch.from_numpy(B_np)

start = time.perf_counter()
C_cpu = torch.matmul(A_cpu, B_cpu)
pytorch_cpu_time = time.perf_counter() - start
print(f"  PyTorch (CPU): {pytorch_cpu_time:.4f} seconds")

# Time PyTorch GPU (if available)
if device == 'cuda':
    A_gpu = A_cpu.to('cuda')
    B_gpu = B_cpu.to('cuda')

    # Warm-up run (first GPU call has extra overhead)
    _ = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()

    # Timed run
    start = time.perf_counter()
    C_gpu = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()  # wait for GPU to finish
    gpu_time = time.perf_counter() - start

    print(f"  PyTorch (GPU): {gpu_time:.4f} seconds")
    print(f"\nSpeedups vs Pure Python:")
    print(f"  NumPy:       {python_time/numpy_time:.0f}x faster")
    print(f"  PyTorch CPU: {python_time/pytorch_cpu_time:.0f}x faster")
    print(f"  PyTorch GPU: {python_time/gpu_time:.0f}x faster")
else:
    print(f"\nSpeedups vs Pure Python:")
    print(f"  NumPy:       {python_time/numpy_time:.0f}x faster")
    print(f"  PyTorch CPU: {python_time/pytorch_cpu_time:.0f}x faster")

Matrix multiplication (500x500):
  Pure Python:   14.4273 seconds
  NumPy (CPU):   0.0041 seconds
  PyTorch (CPU): 0.0092 seconds
  PyTorch (GPU): 0.0002 seconds

Speedups vs Pure Python:
  NumPy:       3494x faster
  PyTorch CPU: 1566x faster
  PyTorch GPU: 80552x faster


In [ ]:
# Large matrix multiplication comparison
size = 4096

# Create large random matrices with NumPy
A_np = np.random.randn(size, size).astype(np.float32)
B_np = np.random.randn(size, size).astype(np.float32)

# Time NumPy (CPU)
start = time.perf_counter()
C_np = np.matmul(A_np, B_np)
numpy_time = time.perf_counter() - start

print(f"Matrix multiplication ({size}x{size}):")
print(f"  NumPy (CPU):   {numpy_time:.4f} seconds")

# Time PyTorch CPU
A_cpu = torch.from_numpy(A_np)
B_cpu = torch.from_numpy(B_np)

start = time.perf_counter()
C_cpu = torch.matmul(A_cpu, B_cpu)
pytorch_cpu_time = time.perf_counter() - start

print(f"  PyTorch (CPU): {pytorch_cpu_time:.4f} seconds")

# Time PyTorch GPU (if available)
if device == 'cuda':
    A_gpu = A_cpu.to('cuda')
    B_gpu = B_cpu.to('cuda')

    # Warm-up run (first GPU call has extra overhead)
    _ = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()

    # Timed run
    start = time.perf_counter()
    C_gpu = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()  # wait for GPU to finish
    gpu_time = time.perf_counter() - start

    print(f"  PyTorch (GPU): {gpu_time:.4f} seconds")
    print(f"\nGPU is {numpy_time/gpu_time:.1f}x faster than NumPy")

Matrix multiplication (4096x4096):
  NumPy (CPU):   1.1602 seconds
  PyTorch (CPU): 1.2312 seconds
  PyTorch (GPU): 0.0467 seconds

GPU is 24.9x faster than NumPy


In [ ]:
# initialize parameters
a = 1.0
learning_rate = 0.1

# data
x = 2.0
y_obs = 10.0

In [ ]:
start = time.perf_counter()

for step in range(100000):
    # Forward pass
    y_pred = a * x

    # calculate loss
    loss = (y_pred - y_obs)**2

    # Compute gradient
    grad_a = 2 * (y_pred - y_obs) * x

    # Update the parameter
    a = a - learning_rate * grad_a

end = time.perf_counter()

print(f"Time without autograd: {end-start:.4f} seconds")

Time without autograd: 0.0434 seconds


In [ ]:
# initialize parameters
a = torch.tensor([1.0], requires_grad=True, device='cuda') # parameter, gradient needed
learning_rate = 0.1

# data
x = torch.tensor([2.0], device='cuda') # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True, device='cuda') # output, gradient needed

In [ ]:
start = time.perf_counter()
for step in range(100000):
    # Forward pass
    y_pred = a * x
    loss = (y_pred - y_obs)**2

    # Backward pass — autograd computes dl/da for us
    loss.backward()

    # Update parameter
    with torch.no_grad():
        a -= learning_rate * a.grad

    # Reset gradient for next step
    a.grad.zero_()
end = time.perf_counter()

print(f"Time with autograd: {end-start:.4f} seconds")

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
import timeit

In [ ]:
# data
x = 2.0
y_obs = 10.0
def train_without_autograd():
    # initialize parameters
    a = 1.0
    learning_rate = 0.1
    for step in range(10000000):
        # Forward pass
        y_pred = a * x

        # calculate loss
        loss = (y_pred - y_obs)**2

        # Compute gradient
        grad_a = 2 * (y_pred - y_obs) * x

        # Update the parameter
        a = a - learning_rate * grad_a

time_without = timeit.timeit(train_without_autograd, number = 10)
print(f"Without autograd: {time_without:.5f} seconds")

Without autograd: 22.77170 seconds


In [ ]:
# data
x = torch.tensor([2.0]) # input, no gradient needed
y_obs = torch.tensor([10.0], requires_grad=True) # output, gradient needed

def train_with_autograd():
    # initialize parameters
    a = torch.tensor([1.0], requires_grad=True) # parameter, gradient needed
    learning_rate = 0.1
    for step in range(1000000):
        # Forward pass
        y_pred = a * x
        loss = (y_pred - y_obs)**2

        # Backward pass — autograd computes dl/da for us
        loss.backward()

        # Update parameter
        with torch.no_grad():
            a -= learning_rate * a.grad

        # Reset gradient for next step
        a.grad.zero_()

time_with = timeit.timeit(train_with_autograd, number=10)
print(f"With autograd: {time_with:.5f} seconds")

KeyboardInterrupt: 